name: Deploy book

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing to the repository
      pull-requests: write  # Allow creating a PR from that branch

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper versioning

    - name: Install latest mdbook
      run: |
        # Fetch the latest mdbook release tag
        tag=$(curl -s 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
        
        # Build the download URL for the latest release
        url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
        
        # Create directory and download mdbook
        mkdir mdbook
        curl -sSL $url | tar -xz --directory=./mdbook
        
        # Add mdbook binary to PATH
        echo "$PWD/mdbook" >> $GITHUB_PATH

    - name: Deploy GitHub Pages
      run: |
        # Generate CLI documentation and inject into the book
        cargo run --package powdr_cli -- --markdown-help > book/src/cli/README.md
        
        # Build the mdBook project
        cd book
        mdbook build
        
        # Set up Git worktree for gh-pages branch
        git worktree add gh-pages
        
        # Configure git user (using a generic email for CI)
        git config user.name "Deploy from CI"
        git config user.email "actions@github.com"
        
        # Switch to gh-pages branch
        cd gh-pages
        
        # Clean the gh-pages branch (avoid keeping old files)
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        
        # Move the built book contents into the gh-pages branch
        mv ../book/* .
        
        # Commit and push the changes to GitHub Pages
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages
